// frontend/src/constants/categoryIcons.ts
// Curated monochrome icon set for categories/cashflow groups. Each icon is stored by its
// stable `key` in the same `icon` TEXT column that used to hold a free-typed emoji — legacy
// emoji values keep rendering as-is (see CategoryGlyph), so this list is additive, not a migration.
import {
  Activity,
  AirVent,
  AlertCircle,
  Anchor,
  Apple,
  Archive,
  Armchair,
  ArrowDownLeft,
  ArrowLeftRight,
  ArrowUpRight,
  Award,
  Baby,
  BadgeDollarSign,
  BadgePercent,
  Banana,
  Banknote,
  Barcode,
  Bath,
  Battery,
  BatteryCharging,
  Bed,
  BedDouble,
  Beef,
  Beer,
  Bell,
  Bike,
  Bitcoin,
  Bluetooth,
  Book,
  BookMarked,
  BookOpen,
  Bookmark,
  Bot,
  Box,
  Boxes,
  Brain,
  Briefcase,
  Brush,
  Bug,
  Building,
  Building2,
  Bus,
  BusFront,
  Cable,
  Cake,
  Calculator,
  Calendar,
  Camera,
  Candy,
  Car,
  CarTaxiFront,
  Caravan,
  Carrot,
  Cat,
  CheckSquare,
  Cherry,
  Cigarette,
  CigaretteOff,
  CircleDollarSign,
  Citrus,
  Clapperboard,
  Clock,
  Cloud,
  CloudRain,
  Code,
  Coffee,
  Coins,
  Compass,
  Construction,
  Cookie,
  Cpu,
  CreditCard,
  Croissant,
  Cross,
  Crown,
  CupSoda,
  Database,
  Diamond,
  Dices,
  Disc,
  Disc3,
  Dog,
  DollarSign,
  DoorOpen,
  Droplet,
  Droplets,
  Drumstick,
  Dumbbell,
  Egg,
  Eye,
  Fan,
  FileSpreadsheet,
  FileText,
  Film,
  Fish,
  FishSymbol,
  Flag,
  Flame,
  FlameKindling,
  Flower,
  Flower2,
  Folder,
  Footprints,
  Fuel,
  Gamepad,
  Gamepad2,
  Gem,
  Gift,
  GlassWater,
  Glasses,
  Globe,
  Goal,
  GraduationCap,
  Group,
  Hammer,
  HardDrive,
  Headphones,
  Heart,
  HeartHandshake,
  HeartPulse,
  HelpCircle,
  HelpingHand,
  Home,
  Hourglass,
  IceCream2,
  Infinity,
  Info,
  Key,
  KeyRound,
  Lamp,
  Landmark,
  Laptop,
  LayoutGrid,
  Library,
  Lightbulb,
  Lock,
  LockKeyhole,
  Luggage,
  Mail,
  MailOpen,
  MapPin,
  Martini,
  Medal,
  Megaphone,
  Mic,
  Microwave,
  Milk,
  Monitor,
  Moon,
  Mountain,
  Music,
  Music2,
  Navigation,
  Newspaper,
  Nut,
  Package,
  Package2,
  PackageCheck,
  PackageOpen,
  PaintBucket,
  Paintbrush,
  Palette,
  Paperclip,
  PawPrint,
  Percent,
  PercentCircle,
  Phone,
  PiggyBank,
  Pill,
  Pin,
  Pizza,
  Plane,
  PlaneLanding,
  PlaneTakeoff,
  Play,
  Plug,
  Pocket,
  Popcorn,
  Presentation,
  Printer,
  QrCode,
  Radio,
  Receipt,
  Recycle,
  Refrigerator,
  Repeat,
  Rocket,
  Rss,
  Sailboat,
  Salad,
  Sandwich,
  Satellite,
  Scale,
  School,
  Scissors,
  Send,
  Server,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  ShowerHead,
  Shuffle,
  Smartphone,
  Smile,
  Sofa,
  Soup,
  Sparkle,
  Sparkles,
  Speaker,
  SprayCan,
  Star,
  Stethoscope,
  Store,
  Sun,
  SunMedium,
  Swords,
  Syringe,
  Tablet,
  Tag,
  Target,
  Tent,
  Terminal,
  Thermometer,
  Ticket,
  Timer,
  Train,
  TrainFront,
  TramFront,
  Trash2,
  TreeDeciduous,
  TreePine,
  Trees,
  TrendingDown,
  TrendingUp,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  User,
  UserCheck,
  Users,
  UsersRound,
  Utensils,
  UtensilsCrossed,
  Vault,
  Video,
  Wallet,
  Wand2,
  Warehouse,
  WashingMachine,
  Watch,
  Wheat,
  Wifi,
  Wine,
  Wrench,
  Zap,
  AlarmClock,
  Axe,
  Backpack,
  BadgeCheck,
  BaggageClaim,
  Bean,
  BedSingle,
  Bird,
  Blinds,
  Blocks,
  CableCar,
  CakeSlice,
  CandyCane,
  Cctv,
  ChefHat,
  CloudLightning,
  CloudSnow,
  CloudSun,
  CookingPot,
  DoorClosed,
  Drill,
  EggFried,
  Eraser,
  Fence,
  Flashlight,
  Grape,
  Guitar,
  Highlighter,
  Hotel,
  IceCream,
  Keyboard,
  LampCeiling,
  LampDesk,
  LampFloor,
  Leaf,
  LifeBuoy,
  Lollipop,
  Milestone,
  MountainSnow,
  Mouse,
  ParkingCircle,
  ParkingMeter,
  Pen,
  PenTool,
  Pencil,
  Piano,
  PocketKnife,
  Projector,
  Rabbit,
  Rainbow,
  Rat,
  ReceiptText,
  Route,
  Shovel,
  SmilePlus,
  Snail,
  Snowflake,
  Sprout,
  Squirrel,
  SunSnow,
  Tags,
  ThermometerSnowflake,
  TrafficCone,
  Turtle,
  Waves,
  Webcam,
  Wind,
  type LucideIcon,
} from 'lucide-react';

export type IconCategoryKey =
  | 'all'
  | 'finance'
  | 'food'
  | 'housing'
  | 'transport'
  | 'shopping'
  | 'tech'
  | 'health'
  | 'work'
  | 'family'
  | 'tools';

export interface IconCategoryDef {
  id: IconCategoryKey;
  label: string;
  Icon: LucideIcon;
}

export const ICON_CATEGORIES: IconCategoryDef[] = [
  { id: 'all', label: 'ทั้งหมด', Icon: LayoutGrid },
  { id: 'finance', label: 'การเงิน', Icon: Coins },
  { id: 'food', label: 'อาหาร/ดื่ม', Icon: Utensils },
  { id: 'transport', label: 'เดินทาง', Icon: Car },
  { id: 'housing', label: 'บ้าน/ที่พัก', Icon: Home },
  { id: 'shopping', label: 'ช้อปปิ้ง', Icon: ShoppingBag },
  { id: 'tech', label: 'ไอที/มีเดีย', Icon: Laptop },
  { id: 'health', label: 'สุขภาพ/กีฬา', Icon: HeartPulse },
  { id: 'work', label: 'งาน/เรียน', Icon: Briefcase },
  { id: 'family', label: 'สัตว์/ครอบครัว', Icon: PawPrint },
  { id: 'tools', label: 'ซ่อม/ทั่วไป', Icon: Wrench },
];

export interface CategoryIconDef {
  key: string;
  label: string;
  category: IconCategoryKey;
  keywords: string;
  Icon: LucideIcon;
}

export const CATEGORY_ICONS: CategoryIconDef[] = [
  { key: 'wallet', label: 'กระเป๋าเงิน / เงินสด', category: 'finance', keywords: 'wallet cash money เงินสด กระเป๋าตังค์', Icon: Wallet },
  { key: 'banknote', label: 'เงินเดือน / ธนบัตร', category: 'finance', keywords: 'banknote salary income เงินเดือน รายได้ แบงก์', Icon: Banknote },
  { key: 'credit-card', label: 'บัตรเครดิต', category: 'finance', keywords: 'credit card payment บัตรเครดิต ผ่อน รูดบัตร', Icon: CreditCard },
  { key: 'coins', label: 'เหรียญ / เงินทอน', category: 'finance', keywords: 'coins change cash เหรียญ เศษตังค์', Icon: Coins },
  { key: 'piggy-bank', label: 'เงินออม / กระปุก', category: 'finance', keywords: 'piggy bank savings เงินออม สะสม หยอดกระปุก', Icon: PiggyBank },
  { key: 'circle-dollar-sign', label: 'รายได้เสริม / ดอลลาร์', category: 'finance', keywords: 'dollar sign side hustle รายได้เสริม จ็อบพิเศษ', Icon: CircleDollarSign },
  { key: 'dollar-sign', label: 'สกุลเงิน / รายได้', category: 'finance', keywords: 'dollar currency money เงิน สกุลเงิน', Icon: DollarSign },
  { key: 'badge-dollar-sign', label: 'โบนัส / ปันผล / อั่งเปา', category: 'finance', keywords: 'bonus dividend ปันผล โบนัส เงินรางวัล 🧧 อั่งเปา แต๊ะเอีย ซองแดง ซองเงิน', Icon: BadgeDollarSign },
  { key: 'mail-open', label: 'อั่งเปา / ซองแดง / ซองเงิน (🧧)', category: 'finance', keywords: '🧧 อั่งเปา ซองแดง แต๊ะเอีย เงินให้ผู้ใหญ่ ซองเงิน โบนัส ของขวัญ red envelope angpao mail open', Icon: MailOpen },
  { key: 'pocket', label: 'กระเป๋าซอง / เงินติดกระเป๋า (🧧)', category: 'finance', keywords: '🧧 pocket ซองเงิน อั่งเปา กระเป๋าเล็ก ซองแดง', Icon: Pocket },
  { key: 'trending-up', label: 'การลงทุน / กำไร', category: 'finance', keywords: 'invest stock profit กำไร หุ้น ขาขึ้น ผลตอบแทน', Icon: TrendingUp },
  { key: 'trending-down', label: 'ขาดทุน / รายจ่ายลดลง', category: 'finance', keywords: 'loss bear ขาดทุน หุ้นตก ค่าเสื่อม', Icon: TrendingDown },
  { key: 'landmark', label: 'ธนาคาร / สถาบันการเงิน', category: 'finance', keywords: 'bank landmark ธนาคาร สถาบันการเงิน กองทุน', Icon: Landmark },
  { key: 'receipt', label: 'บิล / ใบเสร็จ', category: 'finance', keywords: 'receipt bill ใบเสร็จ สลิป ค่าใช้จ่าย', Icon: Receipt },
  { key: 'badge-percent', label: 'ดอกเบี้ย / ส่วนลด', category: 'finance', keywords: 'discount interest percent ดอกเบี้ย ลดราคา โปรโมชั่น', Icon: BadgePercent },
  { key: 'percent', label: 'ภาษี / เปอร์เซ็นต์', category: 'finance', keywords: 'tax vat percent ภาษี หัก ณ ที่จ่าย', Icon: Percent },
  { key: 'percent-circle', label: 'ผลตอบแทน / ROI', category: 'finance', keywords: 'return yield ผลตอบแทน ดอกเบี้ยทบต้น', Icon: PercentCircle },
  { key: 'bitcoin', label: 'คริปโต / บิตคอยน์', category: 'finance', keywords: 'crypto bitcoin blockchain คริปโต เหรียญดิจิทัล', Icon: Bitcoin },
  { key: 'scale', label: 'สมดุล / งบดุล', category: 'finance', keywords: 'balance budget scale งบดุล กฎหมาย ความยุติธรรม', Icon: Scale },
  { key: 'vault', label: 'ตู้เซฟ / สินทรัพย์', category: 'finance', keywords: 'safe vault asset เซฟ ทรัพย์สิน มีค่า มรดก', Icon: Vault },
  { key: 'shield-check', label: 'ประกันภัย / คุ้มครอง', category: 'finance', keywords: 'insurance protect ประกัน ปลอดภัย คุ้มครอง ประกันชีวิต', Icon: ShieldCheck },
  { key: 'shield-alert', label: 'เงินสำรองฉุกเฉิน / ความเสี่ยง', category: 'finance', keywords: 'emergency risk สำรองฉุกเฉิน เสี่ยง ระวัง', Icon: ShieldAlert },
  { key: 'heart-handshake', label: 'กู้ยืม / บริจาค / ช่วยเหลือ', category: 'finance', keywords: 'loan borrow help กู้ยืม หนี้สิน ทำบุญ ยืมเงิน', Icon: HeartHandshake },
  { key: 'helping-hand', label: 'เงินอุดหนุน / สวัสดิการ', category: 'finance', keywords: 'support grant ทุน ช่วยเหลือ สวัสดิการ ประกันสังคม', Icon: HelpingHand },
  { key: 'arrow-down-left', label: 'เงินไหลเข้า / รับเงิน', category: 'finance', keywords: 'cash in deposit income รับเงิน โอนเข้า เงินเข้า', Icon: ArrowDownLeft },
  { key: 'arrow-up-right', label: 'เงินไหลออก / โอนเงิน', category: 'finance', keywords: 'cash out transfer expense โอนออก จ่ายเงิน เงินออก', Icon: ArrowUpRight },
  { key: 'arrow-left-right', label: 'โอนระหว่างบัญชี', category: 'finance', keywords: 'transfer move โอนเงิน ย้ายบัญชี เคลื่อนย้าย', Icon: ArrowLeftRight },
  { key: 'calculator', label: 'คำนวณ / บัญชี', category: 'finance', keywords: 'calculate accounting tax บัญชี คำนวณ เครื่องคิดเลข', Icon: Calculator },
  { key: 'qr-code', label: 'พร้อมเพย์ / สแกนจ่าย', category: 'finance', keywords: 'qr promptpay scan จ่ายเงิน สแกน พร้อมเพย์', Icon: QrCode },
  { key: 'barcode', label: 'สแกนบิล / บาร์โค้ด', category: 'finance', keywords: 'barcode scan bill บาร์โค้ด ชำระบิล', Icon: Barcode },
  { key: 'receipt-text', label: 'ใบเสร็จแจกแจง / รายละเอียดบิล', category: 'finance', keywords: 'receipt text invoice bill สลิป บิล ใบแจ้งหนี้ ละเอียด', Icon: ReceiptText },
  { key: 'alarm-clock', label: 'เตือนครบกำหนดชำระ / เตือนหนี้ (⏰)', category: 'finance', keywords: 'due date alarm clock reminder ครบกำหนด เตือนชำระ กำหนดจ่าย หนี้สิน ⏰', Icon: AlarmClock },
  { key: 'utensils', label: 'อาหารทั่วไป', category: 'food', keywords: 'food restaurant อาหาร ร้านอาหาร ข้าว มื้อเที่ยง มื้อเย็น กับข้าว', Icon: Utensils },
  { key: 'utensils-crossed', label: 'รับประทานอาหารนอกบ้าน', category: 'food', keywords: 'dining restaurant กินข้าวนอกบ้าน ดินเนอร์ ภัตตาคาร เลี้ยงฉลอง', Icon: UtensilsCrossed },
  { key: 'coffee', label: 'กาแฟ / คาเฟ่', category: 'food', keywords: 'coffee cafe drink กาแฟ คาเฟ่ ชา ชานม อเมริกาโน่ ลาเต้', Icon: Coffee },
  { key: 'cup-soda', label: 'น้ำอัดลม / ชานม', category: 'food', keywords: 'soda bubble tea น้ำหวาน ชานมไข่มุก น้ำอัดลม เครื่องดื่ม', Icon: CupSoda },
  { key: 'glass-water', label: 'น้ำดื่ม / น้ำเปล่า', category: 'food', keywords: 'water drink น้ำดื่ม น้ำเปล่า แก้วน้ำ', Icon: GlassWater },
  { key: 'beer', label: 'เบียร์ / สังสรรค์', category: 'food', keywords: 'beer pub drink สังสรรค์ ปาร์ตี้ เบียร์ แอลกอฮอล์ ดื่ม', Icon: Beer },
  { key: 'wine', label: 'ไวน์ / ดินเนอร์หรู', category: 'food', keywords: 'wine bar party ไวน์ ดินเนอร์ สุรา บาร์', Icon: Wine },
  { key: 'martini', label: 'ค็อกเทล / บาร์กลางคืน', category: 'food', keywords: 'cocktail bar club ค็อกเทล บาร์ ผับ เหล้า', Icon: Martini },
  { key: 'pizza', label: 'พิซซ่า / ฟาสต์ฟู้ด', category: 'food', keywords: 'pizza fastfood junkfood พิซซ่า ฟาสต์ฟู้ด', Icon: Pizza },
  { key: 'soup', label: 'ก๋วยเตี๋ยว / ซุป / ชาบู', category: 'food', keywords: 'soup noodles ramen ก๋วยเตี๋ยว ชาบู ราเมน สุกี้ หม้อไฟ', Icon: Soup },
  { key: 'sandwich', label: 'เบอร์เกอร์ / แซนด์วิช', category: 'food', keywords: 'sandwich breakfast burger เบอร์เกอร์ แซนด์วิช อาหารเช้า', Icon: Sandwich },
  { key: 'beef', label: 'เนื้อ / สเต็ก / ปิ้งย่าง', category: 'food', keywords: 'meat steak bbq หมูกระทะ ปิ้งย่าง เนื้อ สเต็ก บาร์บีคิว', Icon: Beef },
  { key: 'drumstick', label: 'ไก่ทอด / ของทอด', category: 'food', keywords: 'chicken fried ไก่ทอด ของทอด kfc น่องไก่', Icon: Drumstick },
  { key: 'fish', label: 'ปลา / อาหารทะเล / ซูชิ', category: 'food', keywords: 'fish seafood sushi ซีฟู้ด อาหารทะเล ซาชิมิ ปลาดิบ', Icon: Fish },
  { key: 'salad', label: 'สลัด / อาหารคลีน', category: 'food', keywords: 'salad healthy clean ผัก สลัด อาหารคลีน เพื่อสุขภาพ ลดน้ำหนัก', Icon: Salad },
  { key: 'egg', label: 'ไข่ / วัตถุดิบสด', category: 'food', keywords: 'egg grocery ไข่ วัตถุดิบ ตลาด ไข่ไก่', Icon: Egg },
  { key: 'croissant', label: 'เบเกอรี่ / ครัวซองต์', category: 'food', keywords: 'bakery bread croissant ขนมปัง เบเกอรี่ ครัวซองต์ อบ', Icon: Croissant },
  { key: 'cake', label: 'เค้ก / ของหวาน / วันเกิด', category: 'food', keywords: 'cake dessert birthday ขนมหวาน เค้ก ของหวาน วันเกิด เบเกอรี่', Icon: Cake },
  { key: 'ice-cream-2', label: 'ไอศกรีม / ของหวาน', category: 'food', keywords: 'ice cream dessert ไอติม ไอศกรีม ของหวาน ดับร้อน', Icon: IceCream2 },
  { key: 'cookie', label: 'ขนมขบเคี้ยว / คุกกี้', category: 'food', keywords: 'cookie snack sweets ขนม คุกกี้ ของกินเล่น กรุบกรอบ', Icon: Cookie },
  { key: 'candy', label: 'ลูกอม / ช็อกโกแลต', category: 'food', keywords: 'candy sweet chocolate ลูกอม ขนมหวาน ช็อกโกแลต หวาน', Icon: Candy },
  { key: 'apple', label: 'ผลไม้ / เพื่อสุขภาพ', category: 'food', keywords: 'fruit apple healthy ผลไม้ แอปเปิ้ล วิตามิน สุขภาพ', Icon: Apple },
  { key: 'banana', label: 'กล้วย / ผลไม้สด', category: 'food', keywords: 'banana fruit กล้วย ผลไม้สด ตลาดสด', Icon: Banana },
  { key: 'cherry', label: 'เชอร์รี่ / เบอร์รี่', category: 'food', keywords: 'cherry fruit เชอร์รี่ เบอร์รี่ ผลไม้นอก', Icon: Cherry },
  { key: 'citrus', label: 'ส้ม / มะนาว / น้ำผลไม้', category: 'food', keywords: 'citrus orange lemon ส้ม น้ำผลไม้ มะนาว เปรี้ยว', Icon: Citrus },
  { key: 'carrot', label: 'ผักสด / ตลาดสด', category: 'food', keywords: 'carrot vegetable grocery ผัก ตลาดสด แคร์รอต วัตถุดิบ', Icon: Carrot },
  { key: 'wheat', label: 'ข้าวสาร / ธัญพืช', category: 'food', keywords: 'rice wheat grain ข้าวสาร ธัญพืช แป้ง เมล็ดพันธุ์', Icon: Wheat },
  { key: 'milk', label: 'นม / ผลิตภัณฑ์นม', category: 'food', keywords: 'milk dairy นม เนย โยเกิร์ต นมจืด', Icon: Milk },
  { key: 'popcorn', label: 'ป๊อปคอร์น / ขนมดูหนัง', category: 'food', keywords: 'popcorn cinema snack ป๊อปคอร์น ดูหนัง โรงหนัง ขนม', Icon: Popcorn },
  { key: 'cigarette', label: 'บุหรี่ / ยาสูบ', category: 'food', keywords: 'cigarette tobacco smoking บุหรี่ สูบ ควัน', Icon: Cigarette },
  { key: 'cigarette-off', label: 'เลิกบุหรี่', category: 'food', keywords: 'quit smoking เลิกบุหรี่ ประหยัด สุขภาพดี', Icon: CigaretteOff },
  { key: 'snowflake', label: 'น้ำแข็ง / ความเย็นจัด / หิมะ (🧊)', category: 'food', keywords: 'ice cold snowflake frozen cube น้ำแข็ง น้ำแข็งก้อน น้ำแข็งหลอด แช่แข็ง ความเย็น หิมะ 🧊', Icon: Snowflake },
  { key: 'thermometer-snowflake', label: 'ตู้เย็น / แช่แข็ง / อุณหภูมิเย็น (🧊)', category: 'food', keywords: 'freezer cold thermometer ice ตู้เย็น แช่แข็ง ความเย็น น้ำแข็ง ช่องฟรีซ 🧊', Icon: ThermometerSnowflake },
  { key: 'ice-cream', label: 'ไอติมแท่ง / หวานเย็น / ไอศกรีม', category: 'food', keywords: 'ice cream popsicle ไอติม ไอศกรีม หวานเย็น แท่ง ของหวาน 🧊', Icon: IceCream },
  { key: 'cake-slice', label: 'เค้กชิ้น / เบเกอรี่ / ของหวาน', category: 'food', keywords: 'cake slice dessert ชิ้นเค้ก ขนม เค้ก เบเกอรี่', Icon: CakeSlice },
  { key: 'grape', label: 'องุ่น / ผลไม้สด / โรงบ่มไวน์ (🍇)', category: 'food', keywords: 'grape wine fruit องุ่น ผลไม้ พวงองุ่น ผลไม้สด 🍇', Icon: Grape },
  { key: 'bean', label: 'เมล็ดกาแฟ / ถั่ว / ธัญพืช (🫘)', category: 'food', keywords: 'bean coffee coffee bean ถั่ว เมล็ดกาแฟ ธัญพืช วัตถุดิบ 🫘', Icon: Bean },
  { key: 'egg-fried', label: 'ไข่ดาว / อาหารเช้า / ตามสั่ง (🍳)', category: 'food', keywords: 'fried egg breakfast ไข่ดาว อาหารเช้า กระทะ กะเพราไข่ดาว อาหารตามสั่ง 🍳', Icon: EggFried },
  { key: 'cooking-pot', label: 'หม้อต้ม / สุกี้ / ชาบู / ซุป (🍲)', category: 'food', keywords: 'pot stew shabu suki hotpot ชาบู สุกี้ หม้อไฟ แกง ต้ม หม้อต้ม อาหาร 🍲', Icon: CookingPot },
  { key: 'chef-hat', label: 'เชฟ / ค่าทำอาหาร / ครัว (🧑‍🍳)', category: 'food', keywords: 'chef hat cook restaurant พ่อครัว แม่ครัว ทำอาหาร ปรุงอาหาร วัตถุดิบ 🧑‍🍳', Icon: ChefHat },
  { key: 'candy-cane', label: 'ลูกกวาด / ขนมเทศกาล', category: 'food', keywords: 'candy cane sweet ขนม ลูกกวาด คริสต์มาส', Icon: CandyCane },
  { key: 'lollipop', label: 'อมยิ้ม / ลูกอมแท่ง (🍭)', category: 'food', keywords: 'lollipop candy sweet อมยิ้ม ลูกอม หวาน ลูกกวาด 🍭', Icon: Lollipop },
  { key: 'home', label: 'บ้าน / ที่พักอาศัย', category: 'housing', keywords: 'home house บ้าน ที่พัก ที่อยู่ 👪 ครอบครัว family คนในบ้าน', Icon: Home },
  { key: 'building-2', label: 'คอนโด / ค่าส่วนกลาง', category: 'housing', keywords: 'condo building ค่าส่วนกลาง คอนโดมิเนียม ตึก', Icon: Building2 },
  { key: 'building', label: 'อพาร์ตเมนต์ / หอพัก', category: 'housing', keywords: 'apartment dorm หอพัก ห้องเช่า อพาร์ตเมนต์', Icon: Building },
  { key: 'warehouse', label: 'โกดัง / ห้องเก็บของ', category: 'housing', keywords: 'warehouse storage โกดัง เก็บของ คลังสินค้า', Icon: Warehouse },
  { key: 'key', label: 'ค่าเช่า / ดอกเบี้ยบ้าน', category: 'housing', keywords: 'rent key lease ค่าเช่า กุญแจ ผ่อนบ้าน', Icon: Key },
  { key: 'key-round', label: 'กุญแจห้อง / ปลดล็อก', category: 'housing', keywords: 'keyroom lock กุญแจ ห้อง ล็อก', Icon: KeyRound },
  { key: 'bed', label: 'ห้องนอน / เฟอร์นิเจอร์', category: 'housing', keywords: 'bed bedroom mattress เตียง ที่นอน ห้องนอน', Icon: Bed },
  { key: 'bed-double', label: 'โรงแรม / รีสอร์ต', category: 'housing', keywords: 'hotel resort โรงแรม พักผ่อน รีสอร์ต เตียงคู่', Icon: BedDouble },
  { key: 'sofa', label: 'ห้องนั่งเล่น / โซฟา', category: 'housing', keywords: 'living room sofa โซฟา แต่งบ้าน เฟอร์นิเจอร์', Icon: Sofa },
  { key: 'armchair', label: 'เก้าอี้ / มุมทำงานบ้าน', category: 'housing', keywords: 'chair armchair เก้าอี้ พักผ่อน', Icon: Armchair },
  { key: 'bath', label: 'ห้องน้ำ / อ่างอาบน้ำ / สบู่ (🧼)', category: 'housing', keywords: 'bath toilet bathroom ห้องน้ำ สุขภัณฑ์ อ่างอาบน้ำ 🧼 สบู่ อาบน้ำ soap shampoo แชมพู', Icon: Bath },
  { key: 'shower-head', label: 'ฝักบัว / อาบน้ำ / ยาสระผม (🧼)', category: 'housing', keywords: 'shower ฝักบัว อาบน้ำ เครื่องทำน้ำอุ่น 🧼 สบู่ ครีมอาบน้ำ แชมพู soap wash', Icon: ShowerHead },
  { key: 'droplets', label: 'สบู่ / สบู่เหลว / อาบน้ำ / ล้างมือ (🧼)', category: 'housing', keywords: '🧼 soap สบู่ สบู่เหลว ฟองสบู่ ล้างมือ อาบน้ำ ยาสระผม แชมพู ทำความสะอาด droplets wash clean', Icon: Droplets },
  { key: 'spray-can', label: 'สเปรย์ทำความสะอาด / ฆ่าเชื้อ (🧼)', category: 'housing', keywords: '🧼 spray สเปรย์ น้ำยาทำความสะอาด สบู่ แอลกอฮอล์ ฆ่าเชื้อ สุขอนามัย clean hygiene', Icon: SprayCan },
  { key: 'zap', label: 'ค่าไฟฟ้า', category: 'housing', keywords: 'electricity power ค่าไฟ ไฟฟ้า บิลค่าไฟ', Icon: Zap },
  { key: 'droplet', label: 'ค่าน้ำประปา', category: 'housing', keywords: 'water utility ค่าน้ำ ประปา บิลค่าน้ำ', Icon: Droplet },
  { key: 'flame', label: 'แก๊สหุงต้ม / เชื้อเพลิง', category: 'housing', keywords: 'gas flame แก๊ส ถังแก๊ส ค่าแก๊ส ไฟ', Icon: Flame },
  { key: 'lightbulb', label: 'หลอดไฟ / แสงสว่าง', category: 'housing', keywords: 'lightbulb lamp หลอดไฟ เปลี่ยนไฟ ไอเดีย', Icon: Lightbulb },
  { key: 'lamp', label: 'โคมไฟ / แสงสว่าง', category: 'housing', keywords: 'lamp light โคมไฟ ไฟแต่งห้อง', Icon: Lamp },
  { key: 'fan', label: 'พัดลม / ระบายอากาศ', category: 'housing', keywords: 'fan พัดลม ดับร้อน ระบายอากาศ', Icon: Fan },
  { key: 'air-vent', label: 'แอร์ / ล้างแอร์', category: 'housing', keywords: 'air conditioner แอร์ ล้างแอร์ ปรับอากาศ', Icon: AirVent },
  { key: 'refrigerator', label: 'ตู้เย็น / ซ่อมตู้เย็น', category: 'housing', keywords: 'fridge refrigerator ตู้เย็น เครื่องใช้ไฟฟ้า แช่แข็ง', Icon: Refrigerator },
  { key: 'washing-machine', label: 'เครื่องซักผ้า / ซักรีด (🧼)', category: 'housing', keywords: 'laundry wash washing machine เครื่องซักผ้า ซักผ้า ซักอบรีด 🧼 ผงซักฟอก น้ำยาปรับผ้านุ่ม', Icon: WashingMachine },
  { key: 'microwave', label: 'ไมโครเวฟ / เครื่องครัว', category: 'housing', keywords: 'microwave oven ไมโครเวฟ อุ่นอาหาร เตาอบ', Icon: Microwave },
  { key: 'door-open', label: 'ย้ายบ้าน / ประตู', category: 'housing', keywords: 'move door ย้ายบ้าน ประตู เข้าบ้าน', Icon: DoorOpen },
  { key: 'trash-2', label: 'ค่าขยะ / กำจัดของเสีย', category: 'housing', keywords: 'trash garbage waste ค่าขยะ ถังขยะ ทิ้งของ', Icon: Trash2 },
  { key: 'shield', label: 'รปภ. / ระบบความปลอดภัย', category: 'housing', keywords: 'security guard ปลอดภัย รปภ ยาม ค่ารักษาความปลอดภัย', Icon: Shield },
  { key: 'hotel', label: 'โรงแรม / โฮสเทล / ที่พัก (🏨)', category: 'housing', keywords: 'hotel resort stay hostel โรงแรม ที่พัก โฮสเทล รีสอร์ต 🏨', Icon: Hotel },
  { key: 'door-closed', label: 'ประตูปิด / ห้องส่วนตัว', category: 'housing', keywords: 'door room private ประตู ห้องพัก ล็อค ปิดห้อง', Icon: DoorClosed },
  { key: 'bed-single', label: 'เตียงเดี่ยว / ห้องเช่า / หอพัก (🛏️)', category: 'housing', keywords: 'bed single mattress เตียงเดี่ยว ห้องเช่า หอพัก ที่นอน 🛏️', Icon: BedSingle },
  { key: 'lamp-ceiling', label: 'โคมไฟเพดาน / แชนเดอเลียร์', category: 'housing', keywords: 'lamp ceiling light ไฟเพดาน แชนเดอเลียร์ ไฟห้อง', Icon: LampCeiling },
  { key: 'lamp-desk', label: 'โคมไฟโต๊ะทำงาน / ไฟอ่านหนังสือ', category: 'housing', keywords: 'lamp desk work study โคมไฟตั้งโต๊ะ ไฟอ่านหนังสือ', Icon: LampDesk },
  { key: 'lamp-floor', label: 'โคมไฟตั้งพื้น / แต่งห้อง', category: 'housing', keywords: 'lamp floor living room โคมไฟตั้งพื้น แต่งห้อง', Icon: LampFloor },
  { key: 'blinds', label: 'ผ้าม่าน / มู่ลี่กันแดด', category: 'housing', keywords: 'blinds curtain window ผ้าม่าน มู่ลี่ บังแดด ม่าน', Icon: Blinds },
  { key: 'fence', label: 'รั้วบ้าน / ภูมิทัศน์', category: 'housing', keywords: 'fence yard garden รั้วบ้าน กำแพง บริเวณบ้าน สวน', Icon: Fence },
  { key: 'cctv', label: 'กล้องวงจรปิด / ระบบรักษาความปลอดภัย', category: 'housing', keywords: 'cctv security camera วงจรปิด กล้อง รักษาความปลอดภัย รปภ', Icon: Cctv },
  { key: 'car', label: 'รถยนต์ส่วนตัว', category: 'transport', keywords: 'car vehicle auto รถยนต์ รถส่วนตัว ขับรถ', Icon: Car },
  { key: 'car-taxi-front', label: 'แท็กซี่ / Grab / Bolt', category: 'transport', keywords: 'taxi grab bolt ride แท็กซี่ เรียกรถ', Icon: CarTaxiFront },
  { key: 'bus', label: 'รถเมล์ / รถตู้', category: 'transport', keywords: 'bus transit รถเมล์ รถสองแถว รถตู้', Icon: Bus },
  { key: 'bus-front', label: 'รถทัวร์ / บขส.', category: 'transport', keywords: 'tour bus รถทัวร์ ข้ามจังหวัด เดินทางไกล', Icon: BusFront },
  { key: 'train', label: 'รถไฟฟ้า / รถไฟ', category: 'transport', keywords: 'train bts mrt รถไฟฟ้า รถไฟ', Icon: Train },
  { key: 'train-front', label: 'BTS / MRT สายหลัก', category: 'transport', keywords: 'subway metro รถไฟฟ้าใต้ดิน บีทีเอส เอ็มอาร์ที', Icon: TrainFront },
  { key: 'tram-front', label: 'รถราง / รถไฟรางเบา', category: 'transport', keywords: 'tram รถราง โมโนเรล', Icon: TramFront },
  { key: 'bike', label: 'มอเตอร์ไซค์ / วิน / จักรยาน', category: 'transport', keywords: 'bike motorcycle bicycle มอเตอร์ไซค์ จักรยาน วินมอไซค์', Icon: Bike },
  { key: 'fuel', label: 'น้ำมันรถ / เติมน้ำมัน', category: 'transport', keywords: 'fuel gas oil petrol น้ำมัน เติมน้ำมัน ปั๊มน้ำมัน', Icon: Fuel },
  { key: 'battery-charging', label: 'ชาร์จรถไฟฟ้า EV', category: 'transport', keywords: 'ev charging electric car ชาร์จไฟ รถอีวี สถานีชาร์จ', Icon: BatteryCharging },
  { key: 'truck', label: 'ขนส่งสินค้า / ขนของ', category: 'transport', keywords: 'truck delivery ขนของ ย้ายของ รถกระบะ ส่งของ', Icon: Truck },
  { key: 'caravan', label: 'รถบ้าน / แคมป์คาร์', category: 'transport', keywords: 'caravan camper รถบ้าน แคมป์ปิ้ง เที่ยว', Icon: Caravan },
  { key: 'plane', label: 'เครื่องบิน / บินต่างประเทศ', category: 'transport', keywords: 'plane flight เครื่องบิน ตั๋วเครื่องบิน บิน', Icon: Plane },
  { key: 'plane-takeoff', label: 'ตั๋วบินเที่ยวไป', category: 'transport', keywords: 'takeoff flight เที่ยวไป ขาไป เดินทาง', Icon: PlaneTakeoff },
  { key: 'plane-landing', label: 'ตั๋วบินเที่ยวกลับ', category: 'transport', keywords: 'landing flight เที่ยวกลับ ขากลับ ถึงปลายทาง', Icon: PlaneLanding },
  { key: 'ship', label: 'เรือ / ข้ามฟาก / ล่องเรือ', category: 'transport', keywords: 'ship ferry boat เรือ ล่องเรือ ข้ามฟาก ท่าเรือ', Icon: Ship },
  { key: 'sailboat', label: 'เรือใบ / พักผ่อนทางน้ำ', category: 'transport', keywords: 'sailboat sea เรือใบ ทะเล เที่ยวเกาะ', Icon: Sailboat },
  { key: 'anchor', label: 'จอดเรือ / ท่าจอด', category: 'transport', keywords: 'anchor marine สมอ ทะเล', Icon: Anchor },
  { key: 'compass', label: 'ท่องเที่ยว / ผจญภัย', category: 'transport', keywords: 'compass explore travel ท่องเที่ยว เข็มทิศ ผจญภัย', Icon: Compass },
  { key: 'map-pin', label: 'เช็กอิน / พิกัดปลายทาง', category: 'transport', keywords: 'map pin location พิกัด ที่เที่ยว เช็กอิน', Icon: MapPin },
  { key: 'navigation', label: 'GPS / ค่าทางด่วน', category: 'transport', keywords: 'gps navigation toll ทางด่วน ค่านำทาง โทลล์เวย์', Icon: Navigation },
  { key: 'luggage', label: 'กระเป๋าเดินทาง / ทริป', category: 'transport', keywords: 'luggage suitcase baggage กระเป๋าเดินทาง สัมภาระ จัดทริป', Icon: Luggage },
  { key: 'ticket', label: 'ตั๋วโดยสาร / บัตรผ่าน', category: 'transport', keywords: 'ticket pass ตั๋ว บัตรโดยสาร บัตรเข้าชม ตั๋วคอนเสิร์ต', Icon: Ticket },
  { key: 'footprints', label: 'เดิน / วิ่ง / สัญจร', category: 'transport', keywords: 'walk steps ทางเท้า เดิน สัญจร', Icon: Footprints },
  { key: 'route', label: 'เส้นทาง / ทางหลวง / ท่องเที่ยว', category: 'transport', keywords: 'route trip travel highway ทางด่วน ถนน เส้นทาง เดินทางไกล', Icon: Route },
  { key: 'milestone', label: 'หลักกิโลเมตร / จุดพักรถ', category: 'transport', keywords: 'milestone highway rest stop กิโลเมตร ระยะทาง พักรถ', Icon: Milestone },
  { key: 'traffic-cone', label: 'กรวยจราจร / ซ่อมถนน (🚧)', category: 'transport', keywords: 'traffic cone construction กรวยจราจร ด่าน ซ่อมทาง ปิดถนน 🚧', Icon: TrafficCone },
  { key: 'parking-circle', label: 'ค่าจอดรถ / ลานจอด', category: 'transport', keywords: 'parking park car ค่าจอด ที่จอดรถ ลานจอด ค่าบริการ', Icon: ParkingCircle },
  { key: 'parking-meter', label: 'มิเตอร์ที่จอดรถ / ตั๋วจอดรถ', category: 'transport', keywords: 'parking meter ticket ค่าที่จอด ตั๋วจอด หยอดเหรียญ', Icon: ParkingMeter },
  { key: 'cable-car', label: 'กระเช้าลอยฟ้า / เที่ยวภูเขา (🚡)', category: 'transport', keywords: 'cable car gondola ropeway กระเช้า ภูเขา ท่องเที่ยว 🚡', Icon: CableCar },
  { key: 'baggage-claim', label: 'สายพานกระเป๋า / สัมภาระสนามบิน (🛄)', category: 'transport', keywords: 'baggage claim luggage airport สัมภาระ สนามบิน รับกระเป๋า 🛄', Icon: BaggageClaim },
  { key: 'shopping-cart', label: 'รถเข็นช้อปปิ้ง / ซูเปอร์มาร์เก็ต (🛒)', category: 'shopping', keywords: '🛒 supermarket cart grocery shopping cart รถเข็น รถเข็นสินค้า ซูเปอร์มาร์เก็ต ซื้อของเข้าบ้าน ตลาด', Icon: ShoppingCart },
  { key: 'shopping-basket', label: 'ตะกร้าสินค้า / ซูเปอร์ / มินิมาร์ท (🛒)', category: 'shopping', keywords: '🛒 basket shopping basket ตะกร้า ตะกร้าสินค้า มินิมาร์ท ช้อปปิ้ง ซื้อของ ซูเปอร์ รถเข็น 7-11', Icon: ShoppingBasket },
  { key: 'store', label: 'ร้านสะดวกซื้อ / ร้านค้า / มาร์เก็ต (🛒)', category: 'shopping', keywords: '🛒 store shop convenience store ร้านสะดวกซื้อ มินิมาร์ท ร้านของชำ ซื้อของ ซูเปอร์ ตลาด', Icon: Store },
  { key: 'shopping-bag', label: 'ถุงช้อปปิ้ง / ซื้อของ', category: 'shopping', keywords: 'shopping bag mall ห้างสรรพสินค้า ถุงช้อปปิ้ง ซื้อของ 🛒', Icon: ShoppingBag },
  { key: 'package', label: 'พัสดุ / สั่งของออนไลน์ (📦)', category: 'shopping', keywords: '📦 package parcel online shopping พัสดุ ส่งของ กล่อง ช้อปออนไลน์ กล่องพัสดุ ลัง', Icon: Package },
  { key: 'package-2', label: 'กล่องพัสดุ / ลังส่งของ (📦)', category: 'shopping', keywords: '📦 package parcel box กล่องพัสดุ พัสดุ ลัง กล่อง ส่งของ ส่งด่วน ช้อปปิ้ง delivery', Icon: Package2 },
  { key: 'box', label: 'กล่องของ / บรรจุภัณฑ์ (📦)', category: 'shopping', keywords: '📦 box packaging กล่อง ลัง บรรจุภัณฑ์ กล่องพัสดุ', Icon: Box },
  { key: 'boxes', label: 'สต็อกสินค้า / ลังสินค้า (📦)', category: 'shopping', keywords: '📦 boxes inventory stock สต็อก สินค้าคงคลัง หลายกล่อง ลังสินค้า', Icon: Boxes },
  { key: 'package-open', label: 'แกะกล่องพัสดุ / พรีออเดอร์ (📦)', category: 'shopping', keywords: '📦 unboxing pre-order แกะพัสดุ สินค้ามาส่ง กล่องพัสดุ', Icon: PackageOpen },
  { key: 'package-check', label: 'รับพัสดุสำเร็จ (📦)', category: 'shopping', keywords: '📦 delivered package รับของ เช็กพัสดุ สำเร็จ กล่อง', Icon: PackageCheck },
  { key: 'shirt', label: 'เสื้อผ้า / แฟชั่น', category: 'shopping', keywords: 'clothes fashion shirt เสื้อผ้า กางเกง แฟชั่น ชุด', Icon: Shirt },
  { key: 'glasses', label: 'แว่นตา / คอนแทคเลนส์', category: 'shopping', keywords: 'glasses optical แว่นตา ตัดแว่น แว่นกันแดด เลนส์', Icon: Glasses },
  { key: 'watch', label: 'นาฬิกา / สมาร์ตวอทช์', category: 'shopping', keywords: 'watch smartwatch นาฬิกา เครื่องประดับ เวลา', Icon: Watch },
  { key: 'gem', label: 'อัญมณี / เครื่องประดับหรู', category: 'shopping', keywords: 'gem jewelry luxury อัญมณี แหวน สร้อย ทอง เครื่องประดับ', Icon: Gem },
  { key: 'diamond', label: 'เพชร / ของสะสมล้ำค่า', category: 'shopping', keywords: 'diamond luxury เพชร ของสะสม แหวนเพชร', Icon: Diamond },
  { key: 'scissors', label: 'ทำผม / ซาลอน / เสริมสวย', category: 'shopping', keywords: 'hair salon scissors ตัดผม เสริมสวย กรรไกร ร้านทำผม', Icon: Scissors },
  { key: 'sparkles', label: 'ความงาม / สกินแคร์ (🧼)', category: 'shopping', keywords: 'beauty skincare cosmetic เครื่องสำอาง สกินแคร์ คลินิกความงาม สะอาด 🧼', Icon: Sparkles },
  { key: 'tag', label: 'ป้ายราคา / โปรโมชั่น', category: 'shopping', keywords: 'tag discount promo ป้ายราคา เซล ลดราคา', Icon: Tag },
  { key: 'gift', label: 'ของขวัญ / อั่งเปา / วันสำคัญ (🧧)', category: 'shopping', keywords: 'gift present birthday ของขวัญ วันเกิด เทศกาล ปีใหม่ 🧧 อั่งเปา ซองแดง', Icon: Gift },
  { key: 'award', label: 'รางวัล / ความสำเร็จ', category: 'shopping', keywords: 'award badge reward รางวัล โล่ เกียรติบัตร', Icon: Award },
  { key: 'trophy', label: 'ถ้วยรางวัล / ชัยชนะ', category: 'shopping', keywords: 'trophy winner ถ้วยรางวัล ชนะเลิศ ผลงาน', Icon: Trophy },
  { key: 'crown', label: 'สมาชิกพรีเมียม / VIP', category: 'shopping', keywords: 'vip premium crown สมาชิก วีไอพี หรูหรา มงกุฎ', Icon: Crown },
  { key: 'smile', label: 'ความสุข / บันเทิงใจ', category: 'shopping', keywords: 'happy smile fun มีความสุข ให้รางวัลตัวเอง', Icon: Smile },
  { key: 'heart', label: 'ของที่ชอบ / คนพิเศษ', category: 'shopping', keywords: 'heart love favorite ถูกใจ ของที่ชอบ คนรัก', Icon: Heart },
  { key: 'tags', label: 'ป้ายราคาหลายชิ้น / ลดกระหน่ำ (🏷️)', category: 'shopping', keywords: 'tags labels discount sale ป้ายราคา หลายชิ้น ลดราคา โปรโมชั่น 🏷️', Icon: Tags },
  { key: 'backpack', label: 'กระเป๋าเป้ / เดินทาง / ไปเรียน (🎒)', category: 'shopping', keywords: 'backpack bag travel school กระเป๋าเป้ เป้ สะพายหลัง 🎒', Icon: Backpack },
  { key: 'blocks', label: 'ตัวต่อ / เลโก้ / บล็อก / ของสะสม (🧱 🧊)', category: 'shopping', keywords: 'blocks lego toy cube ก้อน บล็อก ตัวต่อ เลโก้ ของเล่น 🧱 🧊', Icon: Blocks },
  { key: 'laptop', label: 'โน้ตบุ๊ก / คอมพิวเตอร์', category: 'tech', keywords: 'laptop computer pc โน้ตบุ๊ก คอม ไอที ทำงาน', Icon: Laptop },
  { key: 'monitor', label: 'จอมอนิเตอร์ / หน้าจอ', category: 'tech', keywords: 'monitor screen จอคอม หน้าจอ แสดงผล', Icon: Monitor },
  { key: 'smartphone', label: 'สมาร์ตโฟน / มือถือ', category: 'tech', keywords: 'phone mobile smartphone มือถือ โทรศัพท์ เคสมือถือ', Icon: Smartphone },
  { key: 'tablet', label: 'แท็บเล็ต / iPad', category: 'tech', keywords: 'tablet ipad ไอแพด แท็บเล็ต วาดรูป', Icon: Tablet },
  { key: 'tv', label: 'โทรทัศน์ / สมาร์ตทีวี', category: 'tech', keywords: 'tv television smart tv โทรทัศน์ ดูทีวี ทีวี', Icon: Tv },
  { key: 'wifi', label: 'อินเทอร์เน็ต / Wi-Fi', category: 'tech', keywords: 'wifi internet เน็ตบ้าน ไวไฟ อินเทอร์เน็ต', Icon: Wifi },
  { key: 'server', label: 'เซิร์ฟเวอร์ / โฮสติ้ง', category: 'tech', keywords: 'server hosting cloud เซิร์ฟเวอร์ โฮสต์ เว็บไซต์', Icon: Server },
  { key: 'cpu', label: 'ฮาร์ดแวร์ / ชิปเซ็ต', category: 'tech', keywords: 'cpu processor hardware ชิป อุปกรณ์คอม ประกอบคอม', Icon: Cpu },
  { key: 'hard-drive', label: 'ฮาร์ดดิสก์ / SSD', category: 'tech', keywords: 'storage ssd hard drive เก็บข้อมูล แฟลชไดรฟ์', Icon: HardDrive },
  { key: 'database', label: 'ฐานข้อมูล / Cloud Data', category: 'tech', keywords: 'database data ฐานข้อมูล คลาวด์ สำรองข้อมูล', Icon: Database },
  { key: 'code', label: 'ซอฟต์แวร์ / เขียนโค้ด', category: 'tech', keywords: 'code programming developer เขียนโค้ด โปรแกรม ซอฟต์แวร์', Icon: Code },
  { key: 'terminal', label: 'เทอร์มินัล / DevOps', category: 'tech', keywords: 'terminal devops cli คำสั่ง คอนโซล', Icon: Terminal },
  { key: 'bot', label: 'AI / บอท / แชตบอต', category: 'tech', keywords: 'ai bot robot chatgpt เอไอ บอท หุ่นยนต์ ปัญญาประดิษฐ์', Icon: Bot },
  { key: 'sparkle', label: 'AI Subscription / อัจฉริยะ', category: 'tech', keywords: 'ai generative magic gpt ซับสคริปชัน', Icon: Sparkle },
  { key: 'wand-2', label: 'เครื่องมือสร้างสรรค์ / เมจิก', category: 'tech', keywords: 'magic edit tools ออกแบบ อัตโนมัติ ครีเอทีฟ', Icon: Wand2 },
  { key: 'cloud', label: 'คลาวด์สตอเรจ / Cloud Storage', category: 'tech', keywords: 'cloud icloud gdrive storage ซื้อพื้นที่ เก็บรูป', Icon: Cloud },
  { key: 'play', label: 'วิดีโอ / YouTube Premium', category: 'tech', keywords: 'play video youtube ดูคลิป ยูทูบ สตรีม', Icon: Play },
  { key: 'music', label: 'ดนตรี / เพลง', category: 'tech', keywords: 'music audio ดนตรี เพลง เครื่องดนตรี คอร์ด', Icon: Music },
  { key: 'music-2', label: 'สตรีมมิ่งเพลง / Spotify / Apple Music', category: 'tech', keywords: 'spotify apple music streaming สตรีมมิ่ง ฟังเพลง', Icon: Music2 },
  { key: 'film', label: 'ภาพยนตร์ / Netflix / Disney+', category: 'tech', keywords: 'movie netflix film ซีรีส์ หนัง สตรีมมิ่ง โรงภาพยนตร์', Icon: Film },
  { key: 'video', label: 'ถ่ายวิดีโอ / โปรดักชัน', category: 'tech', keywords: 'video camera vlog อัดคลิป ถ่ายวิดีโอ ยูทูบเบอร์', Icon: Video },
  { key: 'camera', label: 'กล้องดิจิทัล / อุปกรณ์ถ่ายภาพ', category: 'tech', keywords: 'camera photo lens กล้อง เลนส์ ช่างภาพ', Icon: Camera },
  { key: 'headphones', label: 'หูฟัง / ลำโพงส่วนตัว', category: 'tech', keywords: 'headphones earphone audio หูฟัง เสียงเพลง ดนตรี', Icon: Headphones },
  { key: 'speaker', label: 'ลำโพง / เครื่องเสียง', category: 'tech', keywords: 'speaker sound ลําโพง เครื่องเสียง บลูทูธ', Icon: Speaker },
  { key: 'mic', label: 'ไมโครโฟน / ร้องเพลง / พอดแคสต์', category: 'tech', keywords: 'mic podcast record ร้องเพลง คาราโอเกะ จัดรายการ', Icon: Mic },
  { key: 'gamepad', label: 'เครื่องเกมคอนโซล / PlayStation / Switch', category: 'tech', keywords: 'console playstation switch xbox เครื่องเล่นเกม', Icon: Gamepad },
  { key: 'gamepad-2', label: 'เกม / Steam / เติมเกม', category: 'tech', keywords: 'game steam topup เติมเกม ซื้อเกม อีสปอร์ต', Icon: Gamepad2 },
  { key: 'dices', label: 'สลากกินแบ่ง / บอร์ดเกม / ลุ้นโชค', category: 'tech', keywords: 'dice lottery boardgame หวย สลาก เสี่ยงโชค บอร์ดเกม', Icon: Dices },
  { key: 'disc', label: 'แผ่นซอฟต์แวร์ / สื่อบันทึก', category: 'tech', keywords: 'cd dvd disc แผ่นเกม แผ่นโปรแกรม', Icon: Disc },
  { key: 'disc-3', label: 'แผ่นเสียงไวนิล / เพลงสะสม', category: 'tech', keywords: 'vinyl record turntable แผ่นเสียง สะสม', Icon: Disc3 },
  { key: 'clapperboard', label: 'ภาพยนตร์ / สตูดิโอ', category: 'tech', keywords: 'movie production film slate ถ่ายทำ สตูดิโอ', Icon: Clapperboard },
  { key: 'radio', label: 'วิทยุ / พอดแคสต์', category: 'tech', keywords: 'radio broadcast วิทยุ สัญญาณ คลื่น', Icon: Radio },
  { key: 'newspaper', label: 'หนังสือพิมพ์ / ข่าวสาร', category: 'tech', keywords: 'news newspaper journal ข่าว สำนักข่าว สื่อ', Icon: Newspaper },
  { key: 'rss', label: 'บทความ / ฟีดข่าว', category: 'tech', keywords: 'rss feed blog บทความ ฟีด สมัครอ่าน', Icon: Rss },
  { key: 'bell', label: 'การแจ้งเตือน / บริการรายเดือน', category: 'tech', keywords: 'notification alert bell แจ้งเตือน เตือนชำระ', Icon: Bell },
  { key: 'repeat', label: 'สมาชิกรายเดือน / ตัดบัตรอัตโนมัติ', category: 'tech', keywords: 'subscription recurring repeat รายเดือน รายปี ต่ออายุ', Icon: Repeat },
  { key: 'battery', label: 'แบตเตอรี่ / ถ่านไฟฉาย', category: 'tech', keywords: 'battery power bank แบต พาวเวอร์แบงก์ ถ่าน', Icon: Battery },
  { key: 'cable', label: 'สายชาร์จ / สายเคเบิล', category: 'tech', keywords: 'cable wire usb สายชาร์จ อุปกรณ์เสริม', Icon: Cable },
  { key: 'plug', label: 'ปลั๊กไฟ / หัวชาร์จ', category: 'tech', keywords: 'plug adapter charger ปลั๊กไฟ อะแดปเตอร์ หัวชาร์จ', Icon: Plug },
  { key: 'bluetooth', label: 'บลูทูธ / แกดเจ็ตไร้สาย', category: 'tech', keywords: 'bluetooth wireless เชื่อมต่อ บลูทูธ อุปกรณ์ไร้สาย', Icon: Bluetooth },
  { key: 'satellite', label: 'จานดาวเทียม / เครือข่าย', category: 'tech', keywords: 'satellite network ดาวเทียม เสาสัญญาณ', Icon: Satellite },
  { key: 'rocket', label: 'สตาร์ตอัป / โครงการใหม่', category: 'tech', keywords: 'startup launch rocket ยิงแอด โครงการ ก้าวกระโดด', Icon: Rocket },
  { key: 'lock', label: 'ความปลอดภัยไอที / พาสเวิร์ด', category: 'tech', keywords: 'security password lock รหัสผ่าน คีย์ล็อก ความปลอดภัย', Icon: Lock },
  { key: 'lock-keyhole', label: 'การปกป้องข้อมูล / ล็อกเกอร์', category: 'tech', keywords: 'lock private ปลอดภัย ความลับ ล็อกเกอร์', Icon: LockKeyhole },
  { key: 'keyboard', label: 'คีย์บอร์ด / แป้นพิมพ์ (⌨️)', category: 'tech', keywords: 'keyboard mechanical typing คีย์บอร์ด แป้นพิมพ์ ⌨️', Icon: Keyboard },
  { key: 'mouse', label: 'เมาส์ / อุปกรณ์คอมพิวเตอร์ (🖱️)', category: 'tech', keywords: 'mouse pointer click เมาส์ อุปกรณ์ไอที คอมพิวเตอร์ 🖱️', Icon: Mouse },
  { key: 'projector', label: 'โปรเจกเตอร์ / โฮมเธียเตอร์', category: 'tech', keywords: 'projector cinema presentation ฉายหนัง โปรเจกเตอร์ จอภาพ', Icon: Projector },
  { key: 'webcam', label: 'เว็บแคม / ประชุมออนไลน์ / สตรีม', category: 'tech', keywords: 'webcam camera meeting live stream กล้องคอม ประชุม ไลฟ์', Icon: Webcam },
  { key: 'heart-pulse', label: 'ตรวจสุขภาพ / อัตราเต้นหัวใจ', category: 'health', keywords: 'health heart pulse ตรวจสุขภาพ คลื่นหัวใจ รักษา', Icon: HeartPulse },
  { key: 'pill', label: 'ยา / วิตามิน / อาหารเสริม', category: 'health', keywords: 'medicine pill vitamin ค่ายา วิตามิน อาหารเสริม ร้านขายยา', Icon: Pill },
  { key: 'stethoscope', label: 'พบแพทย์ / โรงพยาบาล / คลินิก', category: 'health', keywords: 'doctor clinic hospital หมอ คลินิก โรงพยาบาล ตรวจโรค', Icon: Stethoscope },
  { key: 'dumbbell', label: 'ฟิตเนส / ยิม / ยกน้ำหนัก', category: 'health', keywords: 'gym fitness workout ยกเวท ฟิตเนส ออกกำลังกาย กล้าม', Icon: Dumbbell },
  { key: 'activity', label: 'เช็กสมรรถภาพ / กิจกรรมกีฬา', category: 'health', keywords: 'activity exercise cardio คาร์ดิโอ วิ่ง สมรรถภาพ', Icon: Activity },
  { key: 'syringe', label: 'วัคซีน / ฉีดยา / เจาะเลือด', category: 'health', keywords: 'vaccine injection syringe วัคซีน ฉีดยา โรงพยาบาล', Icon: Syringe },
  { key: 'cross', label: 'ปฐมพยาบาล / กาชาด', category: 'health', keywords: 'first aid red cross ปฐมพยาบาล ยาสามัญ กาชาด ฉุกเฉิน', Icon: Cross },
  { key: 'thermometer', label: 'ไข้หวัด / ยาพารา / ป่วย', category: 'health', keywords: 'fever thermometer sick ปรอท เป็นไข้ ป่วย ไม่สบาย', Icon: Thermometer },
  { key: 'brain', label: 'สุขภาพใจ / พัฒนาทักษะสมอง', category: 'health', keywords: 'mental health brain สมอง สุขภาพจิต จิตบำบัด ความคิด', Icon: Brain },
  { key: 'eye', label: 'สุขภาพสายตา / ตรวจวัดสายตา', category: 'health', keywords: 'vision eye optometry สายตา จักษุ เลสิก คอนแทค', Icon: Eye },
  { key: 'medal', label: 'วิ่งมินิมาราธอน / การแข่งขัน', category: 'health', keywords: 'medal marathon race วิ่งมาราธอน เหรียญรางวัล งานวิ่ง', Icon: Medal },
  { key: 'swords', label: 'ศิลปะการต่อสู้ / เทควันโด / มวย', category: 'health', keywords: 'martial arts boxing มวย เทควันโด ฟันดาบ ต่อสู้', Icon: Swords },
  { key: 'mountain', label: 'เดินป่า / ปีนเขา', category: 'health', keywords: 'hiking mountain outdoor ปีนเขา เดินป่า ธรรมชาติ กิจกรรม', Icon: Mountain },
  { key: 'tent', label: 'แคมป์ปิ้ง / ลานกางเต็นท์', category: 'health', keywords: 'camping tent outdoor แคมป์ กางเต็นท์ พักแรม เดินป่า', Icon: Tent },
  { key: 'smile-plus', label: 'สุขภาพจิตบวก / ความสุข / คลายเครียด', category: 'health', keywords: 'happy mental smile health ความสุข จิตใจ อารมณ์ดี เบิกบาน', Icon: SmilePlus },
  { key: 'life-buoy', label: 'ห่วงยางกู้ชีพ / ประกันอุบัติเหตุ (🛟)', category: 'health', keywords: 'safety lifebuoy swim rescue ห่วงยาง ปลอดภัย กู้ชีพ ว่ายน้ำ 🛟', Icon: LifeBuoy },
  { key: 'briefcase', label: 'งานประจำ / ธุรกิจ / ออฟฟิศ', category: 'work', keywords: 'work job office business งานประจำ ออฟฟิศ บริษัท ธุรกิจ', Icon: Briefcase },
  { key: 'graduation-cap', label: 'การศึกษา / มหาวิทยาลัย / ปริญญา', category: 'work', keywords: 'degree university graduation การศึกษา รับปริญญา มหาวิทยาลัย', Icon: GraduationCap },
  { key: 'school', label: 'โรงเรียน / ค่าเทอม / สถาบัน', category: 'work', keywords: 'school tuition โรงเรียน ค่าเทอม ค่าเล่าเรียน ลูก', Icon: School },
  { key: 'book', label: 'ตำราเรียน / หนังสือวิชาการ', category: 'work', keywords: 'textbook book study หนังสือเรียน คู่มือ ตำรา', Icon: Book },
  { key: 'book-open', label: 'หนังสืออ่านเล่น / คอร์สเรียน', category: 'work', keywords: 'reading book learn หนังสือ อ่านหนังสือ คอร์ส', Icon: BookOpen },
  { key: 'book-marked', label: 'บุ๊กมาร์ก / รายการอ่าน', category: 'work', keywords: 'bookmark read note บันทึก แหล่งอ้างอิง', Icon: BookMarked },
  { key: 'library', label: 'ห้องสมุด / สื่อค้นคว้า', category: 'work', keywords: 'library research ห้องสมุด หอจดหมายเหตุ ค้นคว้า', Icon: Library },
  { key: 'presentation', label: 'สัมมนา / พรีเซนเทชัน / บรรยาย', category: 'work', keywords: 'presentation seminar training สัมมนา บรรยาย อบรม เวิร์กช็อป', Icon: Presentation },
  { key: 'file-text', label: 'เอกสาร / สัญญา / ใบแจ้งหนี้', category: 'work', keywords: 'document contract invoice เอกสาร สัญญา ใบเสนอราคา', Icon: FileText },
  { key: 'file-spreadsheet', label: 'สเปรดชีต / บัญชี / Excel', category: 'work', keywords: 'spreadsheet excel table บัญชี งบการเงิน เอ็กเซล ตาราง', Icon: FileSpreadsheet },
  { key: 'folder', label: 'แฟ้มงาน / จัดเก็บงาน', category: 'work', keywords: 'folder archive directory โฟลเดอร์ แฟ้มงาน เก็บงาน', Icon: Folder },
  { key: 'archive', label: 'คลังเอกสาร / เอกสารประวัติ', category: 'work', keywords: 'archive box records เอกสารเก่า บันทึกย้อนหลัง', Icon: Archive },
  { key: 'clock', label: 'ชั่วโมงทำงาน / ล่วงเวลา OT', category: 'work', keywords: 'clock time overtime โอที ค่าล่วงเวลา ตอกบัตร เวลา', Icon: Clock },
  { key: 'timer', label: 'จับเวลา / พักเบรก / โฟกัส', category: 'work', keywords: 'timer stopwatch จับเวลา ประสิทธิภาพ พักเบรก', Icon: Timer },
  { key: 'hourglass', label: 'รองวดเงิน / รอบิล', category: 'work', keywords: 'hourglass wait pending รอเงินเข้า รอชำระ รอคอย', Icon: Hourglass },
  { key: 'calendar', label: 'ปฏิทินงาน / กำหนดการ', category: 'work', keywords: 'calendar schedule date ปฏิทิน ตารางงาน กำหนดจ่าย นัดหมาย', Icon: Calendar },
  { key: 'check-square', label: 'งานที่เสร็จ / To-do list', category: 'work', keywords: 'todo checklist done สิ่งที่ต้องทำ เสร็จสิ้น', Icon: CheckSquare },
  { key: 'mail', label: 'จดหมาย / ไปรษณีย์ / อีเมล', category: 'work', keywords: 'mail email letter อีเมล ซองจดหมาย ส่งจดหมาย 🧧', Icon: Mail },
  { key: 'send', label: 'ส่งงาน / เมสเซนเจอร์', category: 'work', keywords: 'send message dispatch ส่งงาน เมสเซนเจอร์ ส่งเอกสาร', Icon: Send },
  { key: 'phone', label: 'โทรศัพท์ / ค่าโทร / ติดต่องาน', category: 'work', keywords: 'phone call ค่าโทรศัพท์ ติดต่อ คุยงาน เบอร์โทร', Icon: Phone },
  { key: 'megaphone', label: 'โฆษณา / การตลาด / ประชาสัมพันธ์', category: 'work', keywords: 'ads marketing promo ยิงแอด โฆษณา การตลาด ประชาสัมพันธ์', Icon: Megaphone },
  { key: 'target', label: 'เป้าหมายธุรกิจ / KPI', category: 'work', keywords: 'target kpi goal ยอดขาย เป้าหมาย ตัวชี้วัด', Icon: Target },
  { key: 'goal', label: 'เป้าหมายชีวิต / แผนการเงิน', category: 'work', keywords: 'goal mission success เป้าหมาย วางแผนอนาคต ธงชัย', Icon: Goal },
  { key: 'printer', label: 'พิมพ์งาน / ปริ้นเตอร์ / ถ่ายเอกสาร', category: 'work', keywords: 'print copy paper ปริ้นต์ เอกสาร ถ่ายเอกสาร หมึกพิมพ์', Icon: Printer },
  { key: 'paperclip', label: 'เครื่องเขียน / อุปกรณ์สำนักงาน', category: 'work', keywords: 'stationery paperclip เครื่องเขียน คลิป หนีบกระดาษ', Icon: Paperclip },
  { key: 'pin', label: 'หมุดปัก / ปักหมุดงานด่วน', category: 'work', keywords: 'pin urgent note หมุด ติดบอร์ด งานด่วน', Icon: Pin },
  { key: 'user', label: 'ค่าใช้จ่ายส่วนบุคคล / เจ้าของกิจการ', category: 'work', keywords: 'user personal me ส่วนตัว เจ้าของ บัญชีเดี่ยว', Icon: User },
  { key: 'users', label: 'เงินเดือนทีมงาน / จ้างลูกน้อง', category: 'work', keywords: 'team staff employees จ้างงาน พนักงาน ทีมงาน ค่าแรง 👪', Icon: Users },
  { key: 'user-check', label: 'ฟรีแลนซ์ / ผู้รับจ้างภายนอก', category: 'work', keywords: 'freelance contractor จ้างทำของ ฟรีแลนซ์ รับงาน', Icon: UserCheck },
  { key: 'pen', label: 'ปากกา / เซ็นสัญญา / จดบันทึก (🖋️)', category: 'work', keywords: 'pen write sign contract ปากกา หมึกซึม เซ็นชื่อ เขียนงาน 🖋️', Icon: Pen },
  { key: 'pen-tool', label: 'ปากกากราฟิก / วาดเวกเตอร์ (✒️)', category: 'work', keywords: 'pentool vector design illustrator ออกแบบ วาดรูป เวกเตอร์ ✒️', Icon: PenTool },
  { key: 'pencil', label: 'ดินสอ / สเก็ตช์ภาพ / ร่างแบบ (✏️)', category: 'work', keywords: 'pencil sketch write ดินสอ วาด ร่างแบบ เขียน ✏️', Icon: Pencil },
  { key: 'highlighter', label: 'ปากกาเน้นข้อความ / ไฮไลต์', category: 'work', keywords: 'highlighter marker study เน้นข้อความ ติว อ่านสอบ ไฮไลต์', Icon: Highlighter },
  { key: 'eraser', label: 'ยางลบ / อุปกรณ์เครื่องเขียน', category: 'work', keywords: 'eraser clean stationery ยางลบ ลบคำผิด แก้ไข', Icon: Eraser },
  { key: 'badge-check', label: 'ใบรับรอง / ผ่านการตรวจสอบ / การันตี', category: 'work', keywords: 'badge verified certificate การันตี ผ่านการอนุมัติ ใบรับรอง รับรอง', Icon: BadgeCheck },
  { key: 'users-round', label: 'ครอบครัว / สมาชิกในบ้าน / พ่อแม่ลูก (👪)', category: 'family', keywords: '👪 family ครอบครัว พ่อแม่ลูก สมาชิกในบ้าน คนในบ้าน ญาติพี่น้อง users round', Icon: UsersRound },
  { key: 'group', label: 'กลุ่มคน / คนในครอบครัว / รวมญาติ (👪)', category: 'family', keywords: '👪 group family ครอบครัว ญาติ สมาชิก รวมกลุ่ม', Icon: Group },
  { key: 'baby', label: 'ทารก / เด็ก / ค่าเลี้ยงดูบุตร (👪)', category: 'family', keywords: 'baby child kid ลูก เด็กแรกเกิด แพมเพิส ค่านม 👪 ครอบครัว family', Icon: Baby },
  { key: 'paw-print', label: 'สัตว์เลี้ยง / อาหารสัตว์', category: 'family', keywords: 'pet animal paw สัตว์เลี้ยง เพ็ทช็อป อาหารสัตว์', Icon: PawPrint },
  { key: 'dog', label: 'สุนัข / หมา / อาบน้ำตัดขน', category: 'family', keywords: 'dog puppy สุนัข หมา ตัดขนสุนัข โรงพยาบาลสัตว์', Icon: Dog },
  { key: 'cat', label: 'แมว / ทาสแมว / ทรายแมว', category: 'family', keywords: 'cat kitten แมว อาหารเปียก ทรายแมว ทาสแมว', Icon: Cat },
  { key: 'fish-symbol', label: 'ปลาตู้ / สัตว์น้ำสวยงาม', category: 'family', keywords: 'aquarium fish ปลาสวยงาม ตู้ปลา อาหารปลา', Icon: FishSymbol },
  { key: 'flower', label: 'ดอกไม้ / ซื้อช่อดอกไม้', category: 'family', keywords: 'flower bouquet ดอกไม้ จัดแจกัน ช่อดอกไม้ ไหว้พระ', Icon: Flower },
  { key: 'flower-2', label: 'ไม้ดอกไม้ประดับ', category: 'family', keywords: 'flora garden ไม้ดอก จัดสวน ต้นไม้ประดับ', Icon: Flower2 },
  { key: 'trees', label: 'ต้นไม้ / จัดสวน / ปุ๋ย', category: 'family', keywords: 'garden tree plant สวน ปลูกต้นไม้ ปุ๋ย ดิน แต่งสวน', Icon: Trees },
  { key: 'tree-pine', label: 'ต้นสน / ธรรมชาติ / ป่าไม้', category: 'family', keywords: 'pine forest nature สน ป่า เขา เที่ยวธรรมชาติ', Icon: TreePine },
  { key: 'tree-deciduous', label: 'สวนผลไม้ / ไร่นา', category: 'family', keywords: 'orchard farm สวน ไร่ เกษตรกร ปลูกผัก', Icon: TreeDeciduous },
  { key: 'sun', label: 'โซลาร์เซลล์ / พลังงานสะอาด', category: 'family', keywords: 'sun solar sunny แดด โซลาร์เซลล์ กลางวัน ไฟโซลาร์', Icon: Sun },
  { key: 'sun-medium', label: 'แสงอาทิตย์ / กลางแจ้ง', category: 'family', keywords: 'sun light outdoor แดด กิจกรรมกลางแจ้ง', Icon: SunMedium },
  { key: 'moon', label: 'กลางคืน / พักผ่อนนอนหลับ', category: 'family', keywords: 'moon night rest พักผ่อน กลางคืน นอน', Icon: Moon },
  { key: 'cloud-rain', label: 'ฤดูฝน / น้ำท่วม / ป้องกันสภาพอากาศ', category: 'family', keywords: 'rain weather storm ฝน หน้าฝน อากาศ', Icon: CloudRain },
  { key: 'umbrella', label: 'ร่ม / ประกันภัยชีวิตและทรัพย์สิน', category: 'family', keywords: 'umbrella protect insurance ร่ม ป้องกัน บรรเทาภัย', Icon: Umbrella },
  { key: 'bug', label: 'กำจัดปลวก / ฉีดแมลง', category: 'family', keywords: 'bug pest control แมลง ปลวก ฉีดยุง กำจัดแมลง', Icon: Bug },
  { key: 'bird', label: 'นก / สัตว์ปีก / กรงนก (🐦)', category: 'family', keywords: 'bird pet animal นก สัตว์ปีก เลี้ยงนก นกแก้ว 🐦 🦜', Icon: Bird },
  { key: 'rabbit', label: 'กระต่าย / สัตว์เลี้ยงตัวเล็ก (🐰)', category: 'family', keywords: 'rabbit bunny pet กระต่าย สัตว์เลี้ยง ขนปุย 🐰', Icon: Rabbit },
  { key: 'turtle', label: 'เต่า / สัตว์เลี้ยง (🐢)', category: 'family', keywords: 'turtle tortoise pet เต่า สัตว์เลี้ยง 🐢', Icon: Turtle },
  { key: 'snail', label: 'หอยทาก / สวน / ช้าแต่มั่นคง (🐌)', category: 'family', keywords: 'snail nature garden หอยทาก สัตว์ สวน 🐌', Icon: Snail },
  { key: 'squirrel', label: 'กระรอก / สัตว์น่ารัก (🐿️)', category: 'family', keywords: 'squirrel pet nature กระรอก 🐿️', Icon: Squirrel },
  { key: 'rat', label: 'หนู / หนูแฮมสเตอร์ (🐹)', category: 'family', keywords: 'rat mouse hamster pet แฮมสเตอร์ หนู สัตว์เลี้ยง 🐹 🐭', Icon: Rat },
  { key: 'leaf', label: 'ใบไม้ / ธรรมชาติ / สิ่งแวดล้อม (🍃)', category: 'family', keywords: 'leaf eco green nature ใบไม้ ต้นไม้ พืช รักษ์โลก 🍃', Icon: Leaf },
  { key: 'sprout', label: 'ต้นอ่อน / เพาะปลูก / เริ่มต้นใหม่ (🌱)', category: 'family', keywords: 'sprout plant grow seed ต้นอ่อน เพาะเมล็ด ปลูกผัก รดน้ำ 🌱', Icon: Sprout },
  { key: 'cloud-sun', label: 'แดดร่มลมตก / ท้องฟ้าสดใส (🌤️)', category: 'family', keywords: 'sun cloud weather อากาศสดใส กลางวัน มีเมฆบางส่วน 🌤️', Icon: CloudSun },
  { key: 'cloud-lightning', label: 'พายุฝนฟ้าคะนอง / ฟ้าผ่า (⛈️)', category: 'family', keywords: 'storm lightning thunder พายุ ฟ้าผ่า ฟ้าร้อง พายุฝน ⛈️', Icon: CloudLightning },
  { key: 'cloud-snow', label: 'หิมะตก / สภาพอากาศเย็นจัด (🌨️ 🧊)', category: 'family', keywords: 'snow cloud winter cold หิมะ หนาว หิมะตก เย็นจัด 🌨️ 🧊', Icon: CloudSnow },
  { key: 'mountain-snow', label: 'ภูเขาหิมะ / ลานสกี (🏔️ 🧊)', category: 'family', keywords: 'mountain snow ski winter ภูเขาหิมะ ลานสกี หนาว หิมะ 🏔️ 🧊', Icon: MountainSnow },
  { key: 'sun-snow', label: 'หนาวแดดออก / ฤดูหนาว', category: 'family', keywords: 'sun snow winter cold แดด หิมะ หนาว อากาศ', Icon: SunSnow },
  { key: 'wind', label: 'สายลม / อากาศถ่ายเท (💨)', category: 'family', keywords: 'wind breeze air ลม พัด เย็นสบาย อากาศ ลมหนาว 💨', Icon: Wind },
  { key: 'rainbow', label: 'สายรุ้ง / ความหวัง / สดใส (🌈)', category: 'family', keywords: 'rainbow colorful hope รุ้ง สายรุ้ง สดใส สีสัน 🌈', Icon: Rainbow },
  { key: 'waves', label: 'คลื่นทะเล / ชายหาด / ทางน้ำ (🌊)', category: 'family', keywords: 'waves sea beach ocean คลื่น ทะเล ชายหาด น้ำ 🌊', Icon: Waves },
  { key: 'wrench', label: 'เครื่องมือช่าง / ซ่อมแซม', category: 'tools', keywords: 'tools repair wrench ซ่อม ช่าง เครื่องมือ ประแจ ปรับปรุง', Icon: Wrench },
  { key: 'hammer', label: 'ค้อน / งานตอกงานไม้', category: 'tools', keywords: 'hammer nail ค้อน ตอก ซ่อมแซม ช่างไม้', Icon: Hammer },
  { key: 'paintbrush', label: 'ทาสี / ตกแต่ง / DIY', category: 'tools', keywords: 'paint diy brush ทาสี แปรงทาสี แต่งบ้าน', Icon: Paintbrush },
  { key: 'paint-bucket', label: 'ถังสี / เคมีภัณฑ์บ้าน', category: 'tools', keywords: 'paint bucket ถังสี สีทาบ้าน ยาแนว', Icon: PaintBucket },
  { key: 'brush', label: 'แปรงทำความสะอาด / งานบ้าน (🧼)', category: 'tools', keywords: 'brush clean แปรง ขัด ล้าง ทำความสะอาด 🧼 สบู่ ซักล้าง', Icon: Brush },
  { key: 'nut', label: 'น็อต / สกรู / อะไหล่', category: 'tools', keywords: 'nut bolt screw น็อต สกรู ข้อต่อ อะไหล่', Icon: Nut },
  { key: 'construction', label: 'งานก่อสร้าง / กั้นทาง / ปรับปรุง', category: 'tools', keywords: 'construction renovate ก่อสร้าง ต่อเติม กั้นไซต์', Icon: Construction },
  { key: 'palette', label: 'งานศิลปะ / งานฝีมือ / วาดรูป', category: 'tools', keywords: 'art hobby palette สี จานสี ศิลปะ วาดรูป งานอดิเรก', Icon: Palette },
  { key: 'flame-kindling', label: 'กองไฟ / ฟืน / ฟืนแคมป์', category: 'tools', keywords: 'fire camp wood แคมป์ไฟ กองไฟ ฟืน', Icon: FlameKindling },
  { key: 'recycle', label: 'รีไซเคิล / ขยะเปียกแยกขยะ', category: 'tools', keywords: 'recycle green แยกขยะ ขายของเก่า รักษ์โลก', Icon: Recycle },
  { key: 'shuffle', label: 'สลับ / ยักย้าย / สุ่ม', category: 'tools', keywords: 'shuffle random สลับ เปลี่ยนแปลง', Icon: Shuffle },
  { key: 'infinity', label: 'บุฟเฟต์ / ไม่จำกัด / เหมาจ่าย', category: 'tools', keywords: 'infinity unlimited buffet บุฟเฟต์ เหมาจ่าย ไม่จำกัด', Icon: Infinity },
  { key: 'star', label: 'รายการโปรด / รายจ่ายประจำ', category: 'tools', keywords: 'star favorite ติดดาว สำคัญ รายการโปรด', Icon: Star },
  { key: 'bookmark', label: 'คั่นหน้า / รายการรอตรวจสอบ', category: 'tools', keywords: 'bookmark save บุ๊กมาร์ก บันทึกไว้', Icon: Bookmark },
  { key: 'flag', label: 'ปักธง / ไฮไลต์ประเด็น', category: 'tools', keywords: 'flag highlight ปักธง ข้อสังเกต ติดตาม', Icon: Flag },
  { key: 'globe', label: 'ธุรกรรมต่างประเทศ / สากล', category: 'tools', keywords: 'globe world travel ทั่วโลก ต่างประเทศ โอนข้ามประเทศ', Icon: Globe },
  { key: 'alert-circle', label: 'เตือนภัย / สำคัญมาก / ระวัง', category: 'tools', keywords: 'alert warning danger เตือน แจ้งเตือน ระวัง ฉุกเฉิน', Icon: AlertCircle },
  { key: 'help-circle', label: 'ข้อสงสัย / ค่าธรรมเนียมไม่แน่ใจ', category: 'tools', keywords: 'help question คำถาม สงสัย ตรวจสอบ', Icon: HelpCircle },
  { key: 'info', label: 'รายละเอียด / ค่าบริการอื่นๆ', category: 'tools', keywords: 'info note ข้อมูล หมายเหตุ ทั่วไป', Icon: Info },
  { key: 'axe', label: 'ขวาน / ตัดไม้ / แคมป์ไฟ (🪓)', category: 'tools', keywords: 'axe chop wood tool ขวาน ฟันไม้ ผ่าฟืน แคมป์ 🪓', Icon: Axe },
  { key: 'drill', label: 'สว่าน / เจาะรู / งานช่าง DIY', category: 'tools', keywords: 'drill hole tool diy สว่าน เจาะผนัง ติดตั้ง ซ่อม', Icon: Drill },
  { key: 'shovel', label: 'พลั่ว / เสียม / งานขุดดินทำสวน', category: 'tools', keywords: 'shovel dig garden soil พลั่ว เสียม ขุดดิน ปลูกต้นไม้ ทำสวน', Icon: Shovel },
  { key: 'flashlight', label: 'ไฟฉาย / ส่องสว่าง / สำรวจ (🔦)', category: 'tools', keywords: 'flashlight torch light emergency ไฟฉาย แสงสว่าง ฉุกเฉิน 🔦', Icon: Flashlight },
  { key: 'guitar', label: 'กีตาร์ / ดนตรีสด / ซ้อมดนตรี (🎸)', category: 'tools', keywords: 'guitar acoustic music rock กีตาร์ ดนตรี กีตาร์โปร่ง กีตาร์ไฟฟ้า 🎸', Icon: Guitar },
  { key: 'piano', label: 'เปียโน / คีย์บอร์ดดนตรี (🎹)', category: 'tools', keywords: 'piano keys keyboard music เปียโน ซ้อมเปียโน ดนตรี 🎹', Icon: Piano },
  { key: 'pocket-knife', label: 'มีดพก / มีดพับ / อเนกประสงค์ (🔪)', category: 'tools', keywords: 'knife pocket knife multitool มีด มีดพก มีดพับ อเนกประสงค์ เดินป่า 🔪', Icon: PocketKnife },
];

export const CATEGORY_ICON_MAP: Record<string, LucideIcon> = Object.fromEntries(
  CATEGORY_ICONS.map((d) => [d.key, d.Icon]),
);

/** Fallback glyph when nothing else applies — matches the old default-emoji convention. */
export const DEFAULT_CATEGORY_ICON: LucideIcon = Package;
